const mongoose = require("mongoose");
const Movie = require("./models/Movie");

require("dotenv").config({ path: __dirname + "/.env" });
const categories = {
  Action: [
    "The Dark Knight",
    "Avengers: Endgame",
    "Black Panther",
    "Gladiator",
    "Mad Max: Fury Road",
    "John Wick",
    "John Wick: Chapter 2",
    "John Wick: Chapter 3",
    "John Wick: Chapter 4",
    "Top Gun: Maverick",
    "Mission: Impossible",
    "Mission: Impossible – Fallout",
    "Mission: Impossible – Dead Reckoning",
    "The Avengers",
    "Avengers: Infinity War",
    "Iron Man",
    "Iron Man 2",
    "Iron Man 3",
    "Captain America: The Winter Soldier",
    "Captain America: Civil War",
    "Thor: Ragnarok",
    "Doctor Strange",
    "Spider-Man: No Way Home",
    "Spider-Man: Homecoming",
    "Spider-Man: Far From Home",
    "Guardians of the Galaxy",
    "Guardians of the Galaxy Vol. 2",
    "Black Widow",
    "Shang-Chi",
    "The Batman",
    "Man of Steel",
    "Wonder Woman",
    "Aquaman",
    "The Matrix",
    "The Matrix Reloaded",
    "The Matrix Revolutions",
    "Edge of Tomorrow",
    "Dune",
    "Dune: Part Two",
    "300",
    "Troy",
    "Casino Royale",
    "Skyfall",
    "No Time to Die",
    "Kingsman: The Secret Service",
    "Extraction",
    "Extraction 2",
    "Nobody",
    "The Equalizer",
    "The Equalizer 2"
  ],

  Comedy: [
    "Home Alone",
    "Home Alone 2",
    "The Mask",
    "Dumb and Dumber",
    "Dumb and Dumber To",
    "Rush Hour",
    "Rush Hour 2",
    "Rush Hour 3",
    "Central Intelligence",
    "Jumanji",
    "Jumanji: Welcome to the Jungle",
    "Jumanji: The Next Level",
    "Free Guy",
    "The Hangover",
    "The Hangover Part II",
    "The Hangover Part III",
    "21 Jump Street",
    "22 Jump Street",
    "Superbad",
    "Step Brothers",
    "Elf",
    "The Intern",
    "Yes Man",
    "Bruce Almighty",
    "Liar Liar",
    "Ace Ventura",
    "Ace Ventura: When Nature Calls",
    "Mr. Bean's Holiday",
    "Johnny English",
    "Johnny English Reborn",
    "Johnny English Strikes Again",
    "Paddington",
    "Paddington 2",
    "Night at the Museum",
    "Night at the Museum: Battle of the Smithsonian",
    "Night at the Museum: Secret of the Tomb",
    "The Pink Panther",
    "The Pink Panther 2",
    "Paul Blart: Mall Cop",
    "Paul Blart: Mall Cop 2",
    "Grown Ups",
    "Grown Ups 2",
    "We're the Millers",
    "The Other Guys",
    "Get Smart",
    "Spy",
    "Tag",
    "Game Night",
    "The Nice Guys",
    "The Proposal"
  ],

  Horror: [
    "The Conjuring",
    "The Conjuring 2",
    "The Conjuring: The Devil Made Me Do It",
    "Insidious",
    "Insidious: Chapter 2",
    "Insidious: Chapter 3",
    "Insidious: The Last Key",
    "Sinister",
    "Sinister 2",
    "It",
    "It Chapter Two",
    "The Nun",
    "The Nun II",
    "Annabelle",
    "Annabelle: Creation",
    "Annabelle Comes Home",
    "A Quiet Place",
    "A Quiet Place Part II",
    "Smile",
    "Smile 2",
    "Scream",
    "Scream 2",
    "Scream 3",
    "Scream 4",
    "Scream VI",
    "The Ring",
    "The Grudge",
    "The Exorcist",
    "The Shining",
    "Doctor Sleep",
    "Halloween",
    "Halloween II",
    "Halloween Kills",
    "Halloween Ends",
    "Friday the 13th",
    "A Nightmare on Elm Street",
    "Final Destination",
    "Final Destination 2",
    "Final Destination 3",
    "Final Destination 5",
    "The Blair Witch Project",
    "Paranormal Activity",
    "Paranormal Activity 2",
    "Paranormal Activity 3",
    "The Babadook",
    "Hereditary",
    "M3GAN",
    "Talk to Me",
    "The Black Phone",
    "Barbarian"
  ],

  Romance: [
    "Titanic",
    "The Notebook",
    "La La Land",
    "Me Before You",
    "The Fault in Our Stars",
    "Pride & Prejudice",
    "The Vow",
    "Dear John",
    "The Longest Ride",
    "Safe Haven",
    "A Walk to Remember",
    "Five Feet Apart",
    "Everything, Everything",
    "Before Sunrise",
    "Before Sunset",
    "Before Midnight",
    "Crazy Rich Asians",
"To All the Boys I've Loved Before",
    "Notting Hill",
    "Pretty Woman",
    "Sleepless in Seattle",
    "You've Got Mail",
    "10 Things I Hate About You",
    "The Holiday",
    "About Time",
    "Love Actually",
    "500 Days of Summer",
    "Eternal Sunshine of the Spotless Mind",
    "Silver Linings Playbook",
    "The Age of Adaline",
    "Brooklyn",
    "Carol",
    "Past Lives",
    "Anyone But You",
    "The Idea of You",
    "Purple Hearts",
    "Through My Window",
    "The Last Song",
    "Letters to Juliet",
    "The Best of Me",
    "Endless Love",
    "The Lucky One",
    "Remember Me",
    "One Day",
    "The Spectacular Now",
    "The Sun Is Also a Star",
    "Chemical Hearts",
    "Midnight Sun",
    "Love, Rosie",
    "The Choice"
  ],

  Drama: [
    "The Shawshank Redemption",
    "Forrest Gump",
    "The Godfather",
    "The Godfather Part II",
    "Fight Club",
    "Good Will Hunting",
    "A Beautiful Mind",
    "The Green Mile",
    "Schindler's List",
    "12 Years a Slave",
    "Whiplash",
    "The Social Network",
    "The Pursuit of Happyness",
    "The Theory of Everything",
    "The Imitation Game",
    "Dead Poets Society",
    "Goodfellas",
    "American Beauty",
    "The Departed",
    "There Will Be Blood",
    "No Country for Old Men",
    "The Revenant",
    "Birdman",
    "Moonlight",
    "Spotlight",
    "Manchester by the Sea",
    "Marriage Story",
    "The Father",
    "Nomadland",
    "Minari",
    "The Whale",
    "Oppenheimer",
    "Killers of the Flower Moon",
    "The Wolf of Wall Street",
    "Catch Me If You Can",
    "The Terminal",
    "Cast Away",
    "Captain Phillips",
    "Sully",
    "American Sniper",
    "Hacksaw Ridge",
    "Fury",
    "1917",
    "Saving Private Ryan",
    "The Pianist",
    "The Last Samurai",
    "Million Dollar Baby",
    "Rocky",
    "Creed",
    "Creed II"
  ],

  "TV Show": [
    "Breaking Bad",
    "Better Call Saul",
    "Stranger Things",
    "Wednesday",
    "The Last of Us",
    "The Walking Dead",
    "Game of Thrones",
    "House of the Dragon",
    "The Witcher",
    "Peaky Blinders",
    "Sherlock",
    "Money Heist",
    "Dark",
   "Yellowstone",
    "The Mandalorian",
    "Loki",
    "The Umbrella Academy",
    "Black Mirror",
    "The Queen's Gambit",
    "Cobra Kai",
    "The Office",
    "Friends",
    "Brooklyn Nine-Nine",
    "How I Met Your Mother",
    "The Big Bang Theory",
    "Modern Family",
    "Prison Break",
    "Lost",
    "Dexter",
    "Vikings",
    "The Last Kingdom",
    "Narcos",
    "Ozark",
    "The Crown",
    "Bridgerton",
    "The Boys",
    "Reacher",
    "Jack Ryan",
    "The Night Agent",
    "The Lincoln Lawyer",
    "You",
    "Lucifer",
    "Suits",
    "Manifest",
    "The Flash",
    "Arrow",
    "Daredevil",
    "Jessica Jones",
    "The Punisher",
    "The Sandman"
  ],

  Anime: [
    "Attack on Titan",
    "Death Note",
    "Demon Slayer",
    "Demon Slayer: Mugen Train",
    "Jujutsu Kaisen",
    "My Hero Academia",
    "Naruto",
    "One Piece",
    "One Punch Man",
    "Bleach",
    "Dragon Ball",
    "Dragon Ball Z",
    "Dragon Ball Super",
    "Hunter x Hunter",
    "Fullmetal Alchemist: Brotherhood",
    "Tokyo Ghoul",
    "Sword Art Online",
    "Black Clover",
    "Fairy Tail",
    "Haikyuu!!",
    "Blue Lock",
    "Chainsaw Man",
    "Spy x Family",
    "Solo Leveling",
    "Vinland Saga",
    "Mob Psycho 100",
    "JoJo's Bizarre Adventure",
    "Code Geass",
    "Steins;Gate",
    "Cowboy Bebop",
    "Neon Genesis Evangelion",
    "Tokyo Revengers",
    "Dr. Stone",
    "Fire Force",
    "Bungo Stray Dogs",
    "The Seven Deadly Sins",
    "Re:Zero",
    "That Time I Got Reincarnated as a Slime",
    "Overlord",
    "Kuroko's Basketball",
    "Your Name",
    "Weathering with You",
    "A Silent Voice",
    "Suzume",
    "Howl's Moving Castle",
    "Spirited Away",
    "My Neighbor Totoro",
    "Princess Mononoke",
    "Castle in the Sky",
    "The Boy and the Heron"
  ],

  Movie: [
    "Avatar",
    "Avengers: Endgame",
    "Black Panther",
    "Guardians of the Galaxy",
    "Inception",
    "Interstellar",
    "Joker",
    "Spider-Man: No Way Home",
    "The Dark Knight",
    "Titanic",
    "The Shawshank Redemption",
    "The Godfather",
    "The Godfather Part II",
    "Pulp Fiction",
    "Forrest Gump",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Order of the Phoenix",
    "The Hunger Games",
    "Catching Fire",
    "The Maze Runner",
    "Jurassic Park",
    "Jurassic World",
    "Transformers",
    "Pacific Rim",
    "Top Gun: Maverick",
    "Dune",
    "Dune: Part Two",
    "Oppenheimer",
    "Barbie",
    "The Batman",
    "Man of Steel",
    "Wonder Woman",
        "Aquaman",
    "Doctor Strange",
    "The Prestige",
    "Gladiator",
    "The Departed",
    "Whiplash",
    "Parasite",
    "The Revenant",
    "A Beautiful Mind",
    "The Social Network",
    "Saving Private Ryan",
    "Kill Bill: Vol. 1"
  ],



  Sports: [
    "Basketball Finals",
    "Cricket World Cup",
    "Football Live",
    "Formula 1 Grand Prix",
    "Olympic Games",
    "PSL Cricket",
    "Tennis Championship",
    "UFC Fight Night",
    "WWE Championship",
    "FIFA World Cup",
    "UEFA Champions League",
    "NBA Finals",
    "Super Bowl",
    "Wimbledon",
    "US Open Tennis",
    "French Open",
    "Australian Open",
    "Formula 1 Monaco Grand Prix",
    "Formula 1 British Grand Prix",
    "Formula 1 Italian Grand Prix",
    "Formula 1 Abu Dhabi Grand Prix",
    "ICC T20 World Cup",
    "ICC Champions Trophy",
    "Asia Cup Cricket",
    "The Ashes",
    "Big Bash League",
    "IPL Cricket",
    "Test Cricket Championship",
    "Pakistan vs India",
    "El Clasico",
    "Premier League",
    "La Liga",
    "Bundesliga",
    "Serie A",
    "Europa League",
    "Copa America",
    "Euro Championship",
    "World Athletics Championship",
    "FIFA Club World Cup",
    "Rugby World Cup",
    "MotoGP",
    "Tour de France",
    "Olympic Football",
    "Olympic Basketball",
    "Olympic Swimming",
    "WrestleMania",
    "UFC Championship",
    "Boxing Championship",
    "Golf Masters",
    "NBA All-Star Game"
  ]
};

async function seedMovies() {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    console.log("MongoDB Connected ✅");

    let added = 0;
    let skipped = 0;

    for (const [category, titles] of Object.entries(categories)) {
      for (const title of titles) {
        const exists = await Movie.findOne({ title });

        if (exists) {
          skipped++;
          continue;
        }

        await Movie.create({
          title,
          description: `${title} - StreamFlix ${category} collection`,
          poster: `https://placehold.co/600x900?text=${encodeURIComponent(title)}`,
          category,
          rating: Number((7 + Math.random() * 2.5).toFixed(1)),
          videoUrl: "https://example.com/video",
          isDeleted: false,
          deletedAt: null
        });

        added++;
      }
    }

    console.log(`Added: ${added}`);
    console.log(`Skipped existing: ${skipped}`);

    const counts = await Movie.aggregate([
      {
        $group: {
          _id: "$category",
          count: { $sum: 1 }
        }
      },
      {
        $sort: { _id: 1 }
      }
    ]);

    console.log("\nCategory Counts:");
    console.table(counts);

    await mongoose.disconnect();
    console.log("\nDone ✅");
  } catch (error) {
    console.error("Seed Error ❌", error);
    process.exit(1);
  }
}

seedMovies();
